name: 'rhythmic_dbt'
version: '1.0.0'
config-version: 2

profile: 'rhythmic_dbt'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
    - "target"
    - "dbt_packages"

models:
  rhythmic_dbt:
    staging:
      +materialized: view
    marts:
      +materialized: table 