#==============================================================================
# Cấu hình Flink tối ưu cho e2-micro
#==============================================================================

# Cấu hình JobManager
jobmanager.memory.process.size: 512mb
jobmanager.memory.heap.size: 384mb
jobmanager.memory.off-heap.size: 128mb
jobmanager.memory.jvm-metaspace.size: 64m
jobmanager.memory.jvm-overhead.min: 32m
jobmanager.memory.jvm-overhead.max: 64m

# Cấu hình TaskManager
taskmanager.memory.process.size: 500mb
taskmanager.memory.framework.heap.size: 64mb
taskmanager.memory.task.heap.size: 256mb
taskmanager.memory.network.min: 32mb
taskmanager.memory.network.max: 64mb
taskmanager.memory.network.fraction: 0.1
taskmanager.memory.managed.size: 64mb
taskmanager.memory.jvm-metaspace.size: 64m
taskmanager.memory.jvm-overhead.min: 32m
taskmanager.memory.jvm-overhead.max: 64m

# Cấu hình chung
taskmanager.numberOfTaskSlots: 1
parallelism.default: 1
io.tmp.dirs: /tmp/flink
state.backend: filesystem
state.checkpoints.dir: file:///tmp/flink/checkpoints
state.savepoints.dir: file:///tmp/flink/savepoints
web.timeout: 10000
heartbeat.interval: 2000
heartbeat.timeout: 10000

# Giảm độ lớn của batch để tiết kiệm bộ nhớ
jobmanager.execution.failover-strategy: region
execution.checkpointing.interval: 10s
execution.checkpointing.max-concurrent-checkpoints: 1
execution.checkpointing.min-pause: 5s 