version: '3.7'

networks:
  flink-network:
    driver: bridge

services:
  jobmanager:
    image: apache/flink:1.17.0-scala_2.12-java11
    container_name: jobmanager
    ports:
      - "8081:8081"
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        state.backend: filesystem
        state.checkpoints.dir: file:///tmp/flink-checkpoints
        state.savepoints.dir: file:///tmp/flink-savepoints
        state.backend.incremental: true
        state.backend.local-recovery: true
        execution.checkpointing.interval: 300000
        execution.checkpointing.timeout: 600000
        execution.checkpointing.min-pause: 5000
        execution.checkpointing.max-concurrent-checkpoints: 1
        jobmanager.memory.process.size: 1024m
        jobmanager.memory.jvm-metaspace.size: 128m
        jobmanager.memory.jvm-overhead.min: 64m
        jobmanager.memory.jvm-overhead.max: 128m
    volumes:
      - ./config:/opt/flink/conf
      - ./checkpoints:/tmp/flink-checkpoints
      - ./savepoints:/tmp/flink-savepoints
      - ./secrets:/opt/flink/secrets
    command: jobmanager
    networks:
      - flink-network

  taskmanager:
    image: apache/flink:1.17.0-scala_2.12-java11
    container_name: taskmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 2
        taskmanager.memory.process.size: 2048m
        taskmanager.memory.managed.size: 512m
        taskmanager.memory.network.min: 128m
        taskmanager.memory.network.max: 256m
        taskmanager.memory.framework.min: 128m
        taskmanager.memory.framework.max: 256m
        taskmanager.memory.jvm-metaspace.size: 128m
        taskmanager.memory.jvm-overhead.min: 64m
        taskmanager.memory.jvm-overhead.max: 128m
    volumes:
      - ./config:/opt/flink/conf
      - ./checkpoints:/tmp/flink-checkpoints
      - ./savepoints:/tmp/flink-savepoints
      - ./secrets:/opt/flink/secrets
    command: taskmanager
    depends_on:
      - jobmanager
    networks:
      - flink-network

  jobs-builder:
    build:
      context: .
      dockerfile: Dockerfile.jobs
    container_name: jobs-builder
    volumes:
      - ./jobs:/opt/flink/jobs
      - ./secrets:/opt/flink/secrets
    environment:
      - KAFKA_BROKER=${KAFKA_BROKER:-kafka-vm:9092}
      - GCS_BUCKET=${GCS_BUCKET:-rhythmic-events}
      - GOOGLE_APPLICATION_CREDENTIALS=/opt/flink/secrets/gcp-credentials.json
    depends_on:
      - jobmanager
      - taskmanager
    networks:
      - flink-network

networks:
  flink-network:
    driver: bridge 