version: '3'

networks:
  flink-network:
    driver: bridge

services:
  jobmanager:
    build:
      context: .
      dockerfile: Dockerfile.jobs
    ports:
      - "8081:8081"
    command: jobmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        state.backend: filesystem
        state.checkpoints.dir: file:///opt/flink/checkpoints
      - KAFKA_BROKER=kafka-vm:9092
      - GCS_BUCKET=rhythmic-bucket
    volumes:
      - ./data/checkpoints:/opt/flink/checkpoints
      - ./secrets:/opt/flink/secrets
      - ./scripts:/opt/flink/scripts
    networks:
      - flink-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/overview"]
      interval: 10s
      timeout: 5s
      retries: 3

  taskmanager:
    build:
      context: .
      dockerfile: Dockerfile.jobs
    depends_on:
      - jobmanager
    command: taskmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 2
        state.backend: filesystem
        state.checkpoints.dir: file:///opt/flink/checkpoints
      - KAFKA_BROKER=kafka-vm:9092
      - GCS_BUCKET=rhythmic-bucket
    volumes:
      - ./data/checkpoints:/opt/flink/checkpoints
      - ./secrets:/opt/flink/secrets
    networks:
      - flink-network
    restart: unless-stopped 