version: '3.8'

services:
  jobmanager:
    build:
      context: .
      dockerfile: Dockerfile.jobs
    ports:
      - "8081:8081"
    command: jobmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        state.backend: filesystem
        state.checkpoints.dir: file:///tmp/flink-checkpoints
    volumes:
      - ./data/checkpoints:/tmp/flink-checkpoints
    networks:
      - flink-network

  taskmanager:
    build:
      context: .
      dockerfile: Dockerfile.jobs
    depends_on:
      - jobmanager
    command: taskmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 2
        state.backend: filesystem
        state.checkpoints.dir: file:///tmp/flink-checkpoints
    volumes:
      - ./data/checkpoints:/tmp/flink-checkpoints
    networks:
      - flink-network

networks:
  flink-network:
    driver: bridge 