version: '3.7'

services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    volumes:
      - ./data/zookeeper:/tmp/zookeeper
    networks:
      - rhythmic-network

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: ${KAFKA_HOST:-kafka-vm}
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "listen_events:1:1,page_view_events:1:1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data/kafka:/kafka/kafka-logs
    depends_on:
      - zookeeper
    networks:
      - rhythmic-network

  producer:
    image: python:3.9-slim
    container_name: producer
    depends_on:
      - kafka
    volumes:
      - ./data:/data
      - ./config:/config
      - ./simple_producer.py:/app/simple_producer.py
    working_dir: /app
    environment:
      - KAFKA_BROKER=kafka:9092
      - H5_DATA_PATH=/data/MillionSongSubset
      - PYTHONUNBUFFERED=1
    command: >
      bash -c "pip install kafka-python h5py &&
               python simple_producer.py"
    networks:
      - rhythmic-network

networks:
  rhythmic-network:
    driver: bridge 