version: '3'

services:
  zookeeper:
    image: wurstmeister/zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      - JVMFLAGS=-Xmx256m -Xms128m
    restart: unless-stopped
    volumes:
      - ./data/zookeeper:/data
    networks:
      - rhythmic-network

  kafka:
    image: wurstmeister/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_HEAP_OPTS: "-Xmx512M -Xms256M"
      KAFKA_LOG_RETENTION_HOURS: 24
      KAFKA_LOG_SEGMENT_BYTES: 100000000
      KAFKA_NUM_PARTITIONS: 1
      KAFKA_DEFAULT_REPLICATION_FACTOR: 1
      KAFKA_NUM_NETWORK_THREADS: 2
      KAFKA_NUM_IO_THREADS: 2
    volumes:
      - ./data/kafka:/var/lib/kafka/data
      - ./config/server.properties:/opt/kafka/config/server.properties
    depends_on:
      - zookeeper
    restart: unless-stopped
    networks:
      - rhythmic-network

  eventsim:
    image: trivadis/eventsim
    container_name: eventsim
    depends_on:
      - kafka
    volumes:
      - ./data/eventsim:/data
    command: >
      --kafka-broker kafka:9092
      --song-data /data/MillionSongSubset
      --config /data/config.json
      --from-time 2023-01-01
      --nusers 1000
      --duration 24h
    networks:
      - rhythmic-network

networks:
  rhythmic-network:
    driver: bridge 